language: python
python:
 - "3.7"
before_install:
  - python --version
  - pip install coverage
install:
 - pip install -r requirements.txt
 
# Avoid Sonar "shallow clone" warnings (Shallow clone detected during the analysis. Some files will miss SCM information.
# This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.)
git:
  depth: 99999

addons:
  sonarcloud:
      organization: "hvidberrrg-github"
      token: ${SONAR_TOKEN}

script:
 - coverage run -m unittest
 - coverage xml -o .coverage.xml

after_success:
  - sonar-scanner -X -Dsonar.verbose=true -Dsonar.python.coverage.reportPaths=.coverage.xml -Dsonar.coverage.exclusions=**/example_*.py -Dsonar.sources=./ -Dsonar.inclusions=**/*.py -Dsonar.organization=hvidberrrg-github -Dsonar.projectKey=hvidberrrg_d-wave -Dsonar.login=${SONAR_TOKEN};

